# Generated by Django 5.0.1 on 2024-04-12 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Sinf nomi')),
                ('rahbar', models.CharField(max_length=500, verbose_name='Sinf Rahbar')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Kitob nomi')),
                ('yosh', models.CharField(max_length=500, verbose_name='Yosh chegarasi')),
                ('description', models.TextField(verbose_name='Kitob Haqida Malumot')),
                ('author', models.CharField(max_length=500, verbose_name='Kim yozgan')),
                ('year', models.CharField(max_length=500, verbose_name='Kitob chiqan yil')),
                ('maktab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uquvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ismi', models.CharField(max_length=500, verbose_name='O`quvchi Ismi')),
                ('Familiya', models.CharField(max_length=500, verbose_name='O`quvchi Familiyasi')),
                ('Sharif', models.CharField(max_length=500, verbose_name='O`quvchi Sharif')),
                ('sinf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sinf')),
            ],
        ),
    ]
