# Generated by Django 5.0.1 on 2024-04-12 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaqt', models.CharField(max_length=500, verbose_name='Kitob topshirish muddati')),
                ('date', models.CharField(max_length=500, verbose_name='Kitob Berilgan Muddat')),
                ('muddat_otdi', models.BooleanField(default=False)),
                ('finish', models.BooleanField(default=False)),
                ('Kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kitob')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.uquvchi')),
            ],
        ),
    ]
