# Generated by Django 5.0.1 on 2024-04-18 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_buy_maktab_sinf_maktab_uquvchi_maktab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formular_soni', models.CharField(max_length=500)),
                ('topshirilgan', models.CharField(max_length=500)),
                ('topshirilmagan', models.CharField(max_length=500)),
                ('jarayonda', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
