# Generated by Django 5.0.1 on 2024-04-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_buy_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Kitob Berilgan Muddat'),
        ),
        migrations.AlterField(
            model_name='buy',
            name='vaqt',
            field=models.DateField(verbose_name='Kitob topshirish muddati'),
        ),
    ]
