# Generated by Django 5.0.1 on 2024-04-18 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_buy_date_alter_buy_vaqt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='date',
        ),
        migrations.AddField(
            model_name='buy',
            name='datess',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='buy',
            name='vaqt',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Kitob topshirish muddati'),
        ),
    ]
