# Generated by Django 5.0.6 on 2024-06-12 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_buy_date_buy_datess_alter_buy_vaqt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tekshiruv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.CharField(choices=[('zo`r', 'zo`r'), ('qoniqarli', 'qoniqarli'), ('qoniqarsiz', 'qoniqarsiz'), ('yomon', 'yomon')], max_length=500)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
        ),
    ]
